version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:16.11.1-ce.0
    container_name: gitlab
    restart: always
    ports:
      - "443:443"
      - "80:80"
      - "222:22"
    volumes:
      - C:\Users\Adrian.wang\gitlab-docker\gitlab\config\config:/etc/gitlab
      - C:\Users\Adrian.wang\gitlab-docker\gitlab\config\log:/var/log/gitlab
      - C:\Users\Adrian.wang\gitlab-docker\gitlab\config\data:/var/opt/gitlab
    networks:
      - gitlab-network

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    volumes:
      - C:\Users\Adrian.wang\gitlab-docker\gitlab-runner\config:/etc/gitlab-runner
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab-network

networks:
  gitlab-network:
    driver: bridge

# 注意: 在使用此文件时，请将 $URL, $GITLAB_CONFIG, $GITLAB_LOG, $GITLAB_DATA 和
# $GIT